FROM openjdk:20-ea-17-jdk

VOLUME /tmp

ARG JAR_FILE
ARG POSTGRESQL_USERNAME
ARG POSTGRESQL_PASSWORD

ENV POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
ENV POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}

COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar","/app.jar"]
