server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: "jdbc:mysql://localhost:3306/simple_crud_app"
    hikari:
      maximum-pool-size: 2
      max-lifetime: 115000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    defer-datasource-initialization: false
