version: '3.8'

services:
  simple-crm-mysql-db:
    image: mysql:8.0
    container_name: simple-crm-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: example
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'